import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header/Index'
import Paint from '@/components/Paint/Index'
import Footer from '@/components/Footer/Index'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Lázaro Oliveira',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} font-lato flex flex-col max-w-2xl w-full relative pb-5 gap-8 min-h-screen`}
      >
        <Header />
        <div className={'pt-5 relative'}>{children}</div>
        <Footer />
      </body>
    </html>
  )
}
